"use client";
/* eslint-disable react-hooks/set-state-in-effect -- each product draft hydrates once from its own local key. */

import { useEffect, useMemo, useRef, useState } from "react";
import { downloadStoryCard } from "@/platform/export/story-card";
import type { StoryChapter } from "@/platform/types";
import { trackProductEvent } from "@/platform/telemetry/client";
import { worldBlueprints, type WorldSlug } from "@/products/worlds/config";

type WorldEvent = { id: string; date: string; title: string; detail?: string; people?: string; place?: string; extra?: string; kind: string };
type WorldState = { title: string; anchorDate: string; events: WorldEvent[] };
type ShareFields = { title: boolean; places: boolean };

const today = () => new Date().toISOString().slice(0, 10);
const blankEvent = (kind: string): Omit<WorldEvent, "id"> => ({ date: today(), title: "", detail: "", people: "", place: "", extra: "", kind });
const scalar = (value: unknown, limit = 180) => typeof value === "string" ? value.trim().slice(0, limit) : typeof value === "number" ? String(value) : "";

function parseCsv(text: string): WorldEvent[] {
  const [head, ...rows] = text.trim().split(/\r?\n/);
  if (!head || !rows.length) return [];
  const columns = head.split(",").map((item) => item.trim().toLowerCase());
  return rows.slice(0, 250).map((row, index) => {
    const values = row.split(",").map((item) => item.trim());
    const pick = (...names: string[]) => values[columns.findIndex((column) => names.includes(column))] ?? "";
    return { id: `csv-${index}-${crypto.randomUUID()}`, date: scalar(pick("date", "occurredat", "timestamp"), 20) || today(), title: scalar(pick("title", "event", "name", "milestone")) || `Imported event ${index + 1}`, detail: scalar(pick("description", "note", "details"), 500) || undefined, people: scalar(pick("people", "person", "platform")) || undefined, place: scalar(pick("place", "location")) || undefined, extra: scalar(pick("metric", "value", "song")) || undefined, kind: scalar(pick("kind", "type")) || "Imported" };
  });
}
function unfoldJson(value: unknown): WorldEvent[] {
  const root = value as { events?: unknown } | unknown[];
  const records = Array.isArray(root) ? root : Array.isArray(root?.events) ? root.events : root && typeof root === "object" ? [root] : [];
  return records.slice(0, 250).map((record, index) => {
    const item = record as Record<string, unknown>;
    return { id: `json-${index}-${crypto.randomUUID()}`, date: scalar(item.date ?? item.occurredAt ?? item.timestamp, 20) || today(), title: scalar(item.title ?? item.name ?? item.event) || `Imported event ${index + 1}`, detail: scalar(item.description ?? item.note ?? item.details, 500) || undefined, people: scalar(item.people ?? item.person ?? item.platform) || undefined, place: scalar(item.place ?? item.location) || undefined, extra: scalar(item.metric ?? item.value ?? item.song) || undefined, kind: scalar(item.kind ?? item.type) || "Imported" };
  });
}
function parseIcs(text: string): WorldEvent[] {
  return text.replace(/\r?\n[ \t]/g, "").split("BEGIN:VEVENT").slice(1, 251).map((block, index) => {
    const read = (name: string) => block.match(new RegExp(`^${name}(?:;[^:]*)?:(.+)$`, "mi"))?.[1]?.trim() ?? "";
    const rawDate = read("DTSTART");
    const date = /^\d{8}/.test(rawDate) ? `${rawDate.slice(0, 4)}-${rawDate.slice(4, 6)}-${rawDate.slice(6, 8)}` : today();
    return { id: `ics-${index}-${crypto.randomUUID()}`, date, title: read("SUMMARY") || `Calendar event ${index + 1}`, detail: scalar(read("DESCRIPTION"), 500) || undefined, place: scalar(read("LOCATION")) || undefined, kind: "Calendar" };
  });
}

export function WorldBuilder({ slug }: { slug: WorldSlug }) {
  const blueprint = worldBlueprints[slug]; const storageKey = `story-platform:world:${slug}:v1`;
  const [state, setState] = useState<WorldState>({ title: "", anchorDate: "", events: [] });
  const [draft, setDraft] = useState<Omit<WorldEvent, "id">>(() => blankEvent(blueprint.kinds[0]));
  const [editing, setEditing] = useState<string | null>(null); const [message, setMessage] = useState(""); const [shareFields, setShareFields] = useState<ShareFields>({ title: false, places: false }); const fileRef = useRef<HTMLInputElement>(null);
  useEffect(() => { try { const saved = window.localStorage.getItem(storageKey); if (!saved) return; const parsed = JSON.parse(saved) as WorldState; if (typeof parsed.title === "string" && Array.isArray(parsed.events)) setState({ title: parsed.title, anchorDate: parsed.anchorDate ?? "", events: parsed.events.filter((event) => event && typeof event.title === "string").slice(0, 500) }); } catch { window.localStorage.removeItem(storageKey); } }, [storageKey]);
  useEffect(() => { window.localStorage.setItem(storageKey, JSON.stringify(state)); }, [state, storageKey]);
  const sorted = useMemo(() => [...state.events].sort((a, b) => a.date.localeCompare(b.date)), [state.events]);
  const places = useMemo(() => [...new Set(state.events.map((event) => event.place).filter(Boolean))] as string[], [state.events]);
  const chapter = useMemo<StoryChapter>(() => ({ id: `${slug}-world`, type: "timeline", title: state.title || blueprint.titlePlaceholder, subtitle: state.events.length ? `${state.events.length} chosen moments · ${places.length} places` : "Add a first memory to begin", metric: state.events.length || undefined, supportingText: blueprint.visualCopy, privacyLevel: "safe", renderVariant: "timeline" }), [blueprint, places.length, slug, state.events.length, state.title]);
  function addOrUpdate() { if (!draft.title.trim()) { setMessage(`Add a ${blueprint.eventLabel.toLowerCase()} first.`); return; } const event: WorldEvent = { ...draft, id: editing ?? crypto.randomUUID(), title: draft.title.trim(), date: draft.date || today(), detail: draft.detail?.trim() || undefined, people: draft.people?.trim() || undefined, place: draft.place?.trim() || undefined, extra: draft.extra?.trim() || undefined }; setState((current) => ({ ...current, events: editing ? current.events.map((item) => item.id === editing ? event : item) : [...current.events, event] })); setEditing(null); setDraft(blankEvent(blueprint.kinds[0])); setMessage(editing ? "Memory updated locally." : "Memory added to this local world."); trackProductEvent("story_viewed", slug); }
  function edit(event: WorldEvent) { const { id, ...next } = event; setEditing(id); setDraft(next); }
  function remove(id: string) { setState((current) => ({ ...current, events: current.events.filter((event) => event.id !== id) })); }
  async function importFile(file: File | undefined) { if (!file) return; if (file.size > 2_000_000) { setMessage("Choose a file under 2 MB; imports stay local in this browser."); return; } try { const text = await file.text(); const incoming = file.name.toLowerCase().endsWith(".ics") ? parseIcs(text) : file.name.toLowerCase().endsWith(".csv") ? parseCsv(text) : unfoldJson(JSON.parse(text)); if (!incoming.length) { setMessage("No supported entries were found. Use JSON records or a CSV with title and date columns."); return; } setState((current) => ({ ...current, events: [...current.events, ...incoming].slice(0, 500) })); setMessage(`Imported ${incoming.length} local ${incoming.length === 1 ? "entry" : "entries"}. Review each one before sharing.`); } catch { setMessage("That file could not be read. Use valid JSON, CSV, or an exported .ics calendar."); } }
  function downloadBackup() { const backup = { version: 1, product: slug, title: state.title || blueprint.titlePlaceholder, anchorDate: state.anchorDate || undefined, events: sorted }; const href = URL.createObjectURL(new Blob([JSON.stringify(backup, null, 2)], { type: "application/json" })); const anchor = document.createElement("a"); anchor.href = href; anchor.download = `${slug}-local-backup.json`; anchor.click(); window.setTimeout(() => URL.revokeObjectURL(href), 500); trackProductEvent("story_exported", slug); }
  async function copySelectedSafeSummary() { const summary = { version: 1, product: slug, eventCount: state.events.length, ...(shareFields.title ? { title: state.title || blueprint.titlePlaceholder } : {}), ...(shareFields.places ? { places: places.slice(0, 8) } : {}), dateRange: sorted.length ? { start: sorted[0].date, end: sorted.at(-1)?.date } : undefined, kinds: [...new Set(state.events.map((event) => event.kind))] }; await navigator.clipboard.writeText(JSON.stringify(summary)); setMessage("Copied a selected share summary. Notes, people labels, raw files, titles and places stay out unless you opt in."); trackProductEvent("share_created", slug); }
  function reset() { if (!window.confirm(`Delete this local ${blueprint.titleLabel.toLowerCase()} and its ${state.events.length} memories from this browser?`)) return; window.localStorage.removeItem(storageKey); setState({ title: "", anchorDate: "", events: [] }); setEditing(null); setDraft(blankEvent(blueprint.kinds[0])); setMessage("The local world was deleted from this browser."); }
  return <div className="product-builder" id={`${slug}-builder`} data-product={slug}>
    <section className="story product-workspace">
      <div className="chapter-head"><div><span className="story-summary-kicker">{blueprint.eyebrow}</span><h2>{blueprint.visualTitle}</h2><p>{blueprint.visualCopy}</p></div></div>
      <div className="builder-card"><h3>Start your world</h3><div className="builder-grid"><label>{blueprint.titleLabel}<input className="share-input" aria-label={blueprint.titleLabel} value={state.title} maxLength={100} onChange={(event) => setState((current) => ({ ...current, title: event.target.value }))} placeholder={blueprint.titlePlaceholder}/></label><label>{blueprint.dateLabel}<input className="share-input" aria-label={blueprint.dateLabel} type="date" value={state.anchorDate} onChange={(event) => setState((current) => ({ ...current, anchorDate: event.target.value }))}/></label></div><div className="premium-actions"><button className="btn btn-soft" onClick={() => fileRef.current?.click()}>Import local file</button><input ref={fileRef} aria-label={`Import ${blueprint.eyebrow} file`} className="file-input" type="file" accept=".json,.csv,.ics,application/json,text/csv,text/calendar" onChange={(event) => void importFile(event.target.files?.[0])}/><button className="btn btn-soft" onClick={downloadBackup} disabled={!state.events.length}>Download local backup</button><button className="btn btn-soft" onClick={reset} disabled={!state.title && !state.events.length}>Delete world</button></div><p className="notice">{blueprint.acceptsIcs ? "Local .ics, JSON and CSV imports are supported. " : "Local JSON and CSV imports are supported. "}{blueprint.acceptsMetrics ? "Metrics are imported as entries; no account connector is claimed. " : ""}Imports stay in this browser.</p></div>
      <div className="builder-card"><h3>{editing ? `Edit ${blueprint.eventLabel.toLowerCase()}` : `Add a ${blueprint.eventLabel.toLowerCase()}`}</h3><div className="builder-grid"><label>{blueprint.eventLabel}<input className="share-input" aria-label={`${blueprint.eyebrow} event title`} value={draft.title} maxLength={140} onChange={(event) => setDraft((current) => ({ ...current, title: event.target.value }))} placeholder={blueprint.eventPlaceholder}/></label><label>Date<input className="share-input" aria-label={`${blueprint.eyebrow} event date`} type="date" value={draft.date} onChange={(event) => setDraft((current) => ({ ...current, date: event.target.value }))}/></label><label>Kind<select className="select" aria-label={`${blueprint.eyebrow} event kind`} value={draft.kind} onChange={(event) => setDraft((current) => ({ ...current, kind: event.target.value }))}>{blueprint.kinds.map((kind) => <option key={kind}>{kind}</option>)}</select></label><label>{blueprint.peopleLabel}<input className="share-input" value={draft.people} maxLength={120} onChange={(event) => setDraft((current) => ({ ...current, people: event.target.value }))}/></label><label>{blueprint.placeLabel}<input className="share-input" value={draft.place} maxLength={120} onChange={(event) => setDraft((current) => ({ ...current, place: event.target.value }))}/></label><label>{blueprint.extraLabel}<input className="share-input" value={draft.extra} maxLength={120} onChange={(event) => setDraft((current) => ({ ...current, extra: event.target.value }))} placeholder={blueprint.extraPlaceholder}/></label><label>{blueprint.detailLabel}<input className="share-input" value={draft.detail} maxLength={500} onChange={(event) => setDraft((current) => ({ ...current, detail: event.target.value }))} placeholder={blueprint.detailPlaceholder}/></label></div><div className="premium-actions"><button className="btn btn-primary" onClick={addOrUpdate}>{editing ? "Save changes" : "Add to world"}</button>{editing ? <button className="btn btn-soft" onClick={() => { setEditing(null); setDraft(blankEvent(blueprint.kinds[0])); }}>Cancel edit</button> : null}</div></div>
      {message ? <div className="notice" role="status">{message}</div> : null}
      <div className="timeline-list" aria-label={`${blueprint.eyebrow} timeline`}>{sorted.length ? sorted.map((event) => <article key={event.id}><div><small>{event.date} · {event.kind}{event.place ? ` · ${event.place}` : ""}</small><h3>{event.title}</h3><p>{event.detail || event.extra || "Private local memory"}</p>{event.people || event.extra ? <div className="metadata-list">{event.people ? <span>{event.people}</span> : null}{event.extra ? <span>{event.extra}</span> : null}</div> : null}</div><div className="premium-actions"><button className="btn btn-soft" onClick={() => edit(event)}>Edit</button><button className="btn btn-soft" onClick={() => remove(event.id)}>Delete</button></div></article>) : <div className="notice">Add a first entry or import a local file. This is a real local-first builder, not a demo-only dashboard.</div>}</div>
    </section>
    {state.events.length ? <section className="story chapter-deck" aria-label={`${blueprint.eyebrow} world story`}><div className="chapter-head"><div><span className="story-summary-kicker">Your world output</span><h3>{state.title || blueprint.titlePlaceholder}</h3><p>{state.events.length} entries across {places.length} places · generated deterministically in this browser.</p></div><div className="premium-actions"><button className="btn btn-primary" onClick={() => void downloadStoryCard(chapter, "vertical", true, "paper")}>Download 9:16 card</button><button className="btn btn-soft" onClick={() => void copySelectedSafeSummary()}>Copy selected safe summary</button></div></div><fieldset className="builder-card"><legend>Optional public fields</legend><p className="notice">No name, place or private note is shared by default.</p><label><input type="checkbox" checked={shareFields.title} onChange={(event) => setShareFields((current) => ({ ...current, title: event.target.checked }))}/> Include the world title</label><label><input type="checkbox" checked={shareFields.places} onChange={(event) => setShareFields((current) => ({ ...current, places: event.target.checked }))}/> Include selected place labels</label></fieldset><div className={`chapter-preview ${blueprint.tone}`}><small>PRIVATE WORLD RECAP</small><h3>{chapter.title}</h3>{chapter.metric ? <strong>{chapter.metric}</strong> : null}<span>{chapter.subtitle}</span><p>{chapter.supportingText}</p><div className="chapter-privacy">Private notes and unselected people labels stay local</div></div></section> : null}
  </div>;
}
